Repository FC-FINAL-TEAM-1/FinalProject_Plus_Be3C_FE, pull requests merged in 2024-12, with the labels that each got.

#7 [fix] 담당 파트 수정(대영)
  src/hooks/useMyStrategyEdit.ts
  src/hooks/useStrategyApi.ts
  src/layouts/Layout.tsx
  src/layouts/StrategyDetailLayout.tsx
  src/pages/StrategyAdd.tsx
  src/pages/mypage/MyStrategyEdit.tsx
  src/stores/useAuthStore.ts
Labels: 🛠️ Fix

#6 [fix] 담당 파트 수정(영은)
  src/api/adminApi.ts
  src/api/userApi.ts
  src/hooks/useUserApi.ts
  src/pages/Notices.tsx
  src/pages/NoticesDetail.tsx
  src/pages/QnaQuestion.tsx
  src/pages/admin/AdminNoticeAdd.tsx
  src/pages/admin/AdminNoticeEdit.tsx
  src/pages/admin/AdminNotices.tsx
  src/pages/admin/AdminNoticesDetail.tsx
  src/pages/mypage/MyPageOpt.tsx
  src/pages/mypage/ProfileEdit.tsx
  src/pages/mypage/QnaDetail.tsx
  src/pages/mypage/QnaList.tsx
  src/stores/useAuthStore.ts
Labels: 🛠️ Fix

#8 [fix] 담당 파트 수정(혜지)
  src/api/adminApi.ts
  src/components/StrategyFilter.tsx
  src/hooks/useAdminApi.ts
  src/pages/SignIn.tsx
  src/pages/StrategyList.tsx
  src/pages/TraderStrategyList.tsx
  src/pages/admin/AdminQna.tsx
  src/pages/admin/AdminQnaDetail.tsx
  src/pages/mypage/MyInterestList.tsx
  src/pages/mypage/MyStrategyList.tsx
  src/utils/dataUtils.ts
Labels: 🛠️ Fix

#12 [fix] 추가 수정사항 작업
  index.html
  src/api/authApi.ts
  src/components/DetailCard.tsx
  src/mocks/faq-list.json
  src/pages/Home.tsx
  src/pages/SignFindPw.tsx
  src/pages/StrategyList.tsx
  src/pages/TraderStrategyList.tsx
  src/pages/mypage/MyInterestList.tsx
  src/pages/mypage/MyStrategyList.tsx
  src/utils/tableUtils.ts
Labels: 🛠️ Fix

#9 [feat] 관리자 페이지 미완성 기능 구현
  src/api/adminApi.ts
  src/hooks/useAdminApi.ts
  src/pages/admin/Admin.tsx
  src/pages/admin/AdminStrategies.tsx
Labels: ✨ Feature, 🎨 Style

#10 [fix] 담당 파트 수정(윤환)
  index.html
  src/components/TextInput.tsx
  src/pages/Home.tsx
  src/pages/QnaQuestion.tsx
  src/pages/SignUpForm.tsx
  src/pages/StrategyList.tsx
  src/pages/TraderStrategyList.tsx
  src/pages/admin/AdminQna.tsx
  src/pages/admin/AdminUsers.tsx
  src/pages/mypage/MyInterestList.tsx
  src/pages/mypage/MyStrategyList.tsx
  src/pages/mypage/QnaDetail.tsx
  src/pages/mypage/QnaList.tsx
Labels: 🛠️ Fix

#14 [fix] 회원가입 API 연동 문제 해결
  src/hooks/useAuthApi.ts
  src/pages/SignUpForm.tsx
Labels: 🛠️ Fix

#17 [Fix] 추가 수정사항 반영 작업
  src/api/commonApi.ts
  src/pages/QnaQuestion.tsx
  src/pages/admin/AdminStrategiesControl.tsx
  src/pages/mypage/QnaAnswer.tsx
  src/pages/mypage/QnaDetail.tsx
  src/pages/mypage/QnaList.tsx
Labels: 🛠️ Fix

#21 [fix] 비밀번호 관련 유효성 검사 문구 수정
  src/pages/SignFindPw.tsx
  src/pages/SignIn.tsx
  src/pages/SignUpForm.tsx
  src/pages/admin/AdminMethods.tsx
  src/pages/admin/AdminStocks.tsx
  src/pages/mypage/MyPagePassword.tsx
Labels: 🛠️ Fix

#28 [settings] AWS EC2 CI/CD 구성
  .github/workflows/deploy.yml
Labels: ⚙️ Settings

#30 [settings] AWS EC2 CI/CD 구성 수정
  .github/workflows/deploy.yml
Labels: ⚙️ Settings

#19 [fix] 프로젝트 최종 수정사항 작업(영은)
  .github/workflows/deploy.yml
  src/pages/Notices.tsx
  src/pages/NoticesDetail.tsx
  src/pages/SignFindPw.tsx
  src/pages/admin/AdminNoticesDetail.tsx
  src/pages/mypage/MyPagePassword.tsx
  src/pages/mypage/Profile.tsx
  src/pages/mypage/QnaAnswer.tsx
Labels: 🛠️ Fix

#32 [fix] 프로젝트 최종 수정사항 작업(대영)
  src/components/Breadcrumb.tsx
  src/hooks/useAuthApi.ts
  src/hooks/useStrategyAdd.ts
Labels: 🛠️ Fix

#31 [fix] 프로젝트 최종 수정사항 작업(혜지)
  README.md
  src/components/Chart.tsx
  src/components/Loading.tsx
  src/components/StrategyFilter.tsx
  src/components/TabButton.tsx
  src/components/Table.tsx
  src/components/Tooltip.tsx
  src/layouts/Footer.tsx
  src/pages/Home.tsx
  src/pages/StrategyList.tsx
  src/pages/admin/Admin.tsx
  src/pages/admin/AdminQna.tsx
Labels: 🛠️ Fix
